spring:
  datasource:
    username: lionel
    password: Mmh28803#
    url: jdbc:mysql://localhost:3306/myblog
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server.servlet.context-path: /api
# #e2f3f5
# #22d1ee
# #3d5af1
# #0e153a
