spring:
  datasource:
    username: lionel
    password: Mmh28803#
    url: jdbc:mysql://localhost:3306/myblog
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true