spring:
  datasource:
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/myblog
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server.servlet.context-path: /api
